cortex:
  endpoint: "http://localhost:9009/api/v1/push"
  auth:
    bearer-token: "${CORTEX_BEARER_TOKEN:}"
  tenant-id: "demo-tenant"
  step: "PT30S"
  batch-size: 10000
  connect-timeout: "PT10S"
  read-timeout: "PT30S"
  compression:
    enabled: true
  retry:
    max-attempts: 3
    initial-delay: "PT1S"
    max-delay: "PT30S"
  buffer:
    enabled: true
    directory: "./metrics-buffer"
    max-file-size: 10485760
  health-check:
    interval: "PT60S"

app:
  name: "cortex-metrics-app"
  version: "3.0.0"
  environment: "development"